### ISSUE TITLE
[Request] Option to set parameter panel to uncollapsed in share links

### ISSUE THREAD

**Issue by Billiam** [sgenoud/replicad#103]
When using the [share](https://studio.replicad.xyz/share) link builder, it would be helpful to allow the model parameters/configuration panel to start expanded rather than collapsed.

This would aid in sharing links to replicad models (especially to users who don't normally use replicad) where the purpose is creating customized models to download.

**Comment by sgenoud** [comment]
Good idea! Not sure if that is going to be easy, but definitely on the todo list!
