### ISSUE TITLE
Request: Export binary STL

### ISSUE THREAD

**Issue by rianadon** [sgenoud/replicad#123]
It would be great to have the option to export binary STL files built into replicad. The `StlAPI_Writer` class used by `blobSTL` does not seem to correctly export the option used to turn on binary stl files, but the `StlAPI.Write` method has a parameter to specify whether ascii or binary files are written.

Here's the function I've been using:

```typescript
const done = oc.StlAPI.Write(shape.wrapped, filename, !binary)
```

Thanks!

**Comment by sgenoud** [comment]
Thanks, I have added it, [blobSTL](https://replicad.xyz/docs/api/classes/Shape#blobstl) now supports a binary option (and you can also export as binary from the workbench).
