### ISSUE TITLE
THREE.Object3D.Default_Up.set(0, 0, 1) should be THREE.Object3D.DEFAULT_UP.set(0, 0, 1);

### ISSUE THREAD

**Issue by r-bt** [sgenoud/replicad#160]
I just cloned the sample app repo and had to update some of the dependencies to get it to run. However, then I got an error that
```
THREE.Object3D.Default_Up is undefined
```

which I had to fix by changing it to 
```
THREE.Object3D.DEFAULT_UP.set(0, 0, 1);
```

**Comment by sgenoud** [comment]
Thanks, I have changed this now!
