### ISSUE TITLE
Plane transformations

### ISSUE THREAD

**Issue by WizardUli** [sgenoud/replicad#17]
It would be handy if we could create new planes as transformations from existing planes similar to `Workplane#transformed` method in CadQuery: https://cadquery.readthedocs.io/en/latest/examples.html#rotated-workplanes

**Comment by sgenoud** [comment]
There is now an implementation of plane transformations. You can [translate them](https://replicad.xyz/docs/api/classes/Plane#translate) or [pivot them](https://replicad.xyz/docs/api/classes/Plane#pivot).

The translation change the origin point, and the pivot the normal of the plane!

Feedback on the API welcome!
