### ISSUE TITLE
Importing STEP?

### ISSUE THREAD

**Issue by lf94** [sgenoud/replicad#2]
Is this already possible and just not well exposed?

I would like to import https://gitlab.steamos.cloud/SteamDeck/hardware/-/blob/master/steamdeck_step_20220202.stp and cut it in half using RepliCAD.

**Comment by sgenoud** [comment]
I have not done anything related to importing STEP (or STL). I will post here when I do!

**Comment by sgenoud** [comment]
I have implemented [import functions for replicad](https://replicad.xyz/docs/api/#import-functions)

This is far from perfect but it (mostly) works.

You can have a look at this small attempt at loading the file [here](https://studio.replicad.xyz/share/https%3A%2F%2Fgist.githubusercontent.com%2Fsgenoud%2Ffdfba30d7df120554e1b1968a81f668e%2Fraw%2F3e5d5713be45cf7b847ad658ff046651da26d976%2Fimport-steam-deck.js). Note that I use cors-anywhere to bypass cors checks and you need to click on the button here: https://cors-anywhere.herokuapp.com/

**Comment by lf94** [comment]
Oh my god, **yes**! Thank you!
