### ISSUE TITLE
line(a, b) vs lineTo([a, b]) argument types

### ISSUE THREAD

**Issue by lf94** [sgenoud/replicad#41]
How come there's this difference?

**Comment by sgenoud** [comment]
This is the different between an absolute and a relative position. When you draw (or sketch) your pointer is at a position (for instance you drew a line to `[5, 2]`. If you do `line(1, 1)` you will draw to the point `[6, 3]`. If you do `lineTo([1, 1])` you will draw to `[1, 1]`

**Comment by sgenoud** [comment]
> The math then only involves 1 type, making everything easier to understand (instead of seeing additional type conversion)

It feels like it would be less welcoming for new users. It makes the API more consistant - but the action behind it is not consistant. In some ways it exposes the inconsistency (`line` and `lineTo` are not the same thing) in a way that aligns with what it does.

> The math then only involves 1 type, making everything easier to understand (instead of seeing additional type conversion)

Note that the conversion is not that complicated to do `line(...vector)` should just work.

There is a bit of inconsistency with the way I do the translate - sometimes I take a vector sometimes a list of distances. I will support everywhere the list of distances for consistency with the "what is absolute and what is relative". I will keep the type overloaded for backwards compatibility but might remove it at some point in the future.

I will close this issue for now - if I see it coming up again and again with newbies I will reconsider!
