### ISSUE TITLE
Visualizer sources

### ISSUE THREAD

**Issue by WizardUli** [sgenoud/replicad#44]
Hello. Are Visualizer's sources available somewhere?
I'd like to use it offline not just so I can work on models without internet but also for easy import of local STEP files.
Thanks

**Comment by raydeleu** [comment]
You can install the Visualiser as a web app, which should allow to use it offline. A real local installation with your own web server is not supported afaik.

**Comment by sgenoud** [comment]
Yes, I confirm that I keep the visualiser private for now, it might be a way to monetize the project at some point.

That said, it might be useful to expose something to make STEP files import a bit easier!
