### ISSUE TITLE
vLineTo?

### ISSUE THREAD

**Issue by lf94** [sgenoud/replicad#5]
Would be useful to avoid additions like the one below:

```javascript
// All measurements in mm

const defaultParams = {
};

const main = ({ Sketcher, sketchCircle }, {}) => {
  const inner = new Sketcher("XZ")
    .vLine(2.5)
    .hLine(6)
    .vLine(2)
    .hLine(3)
    .vLine(3)
    .hLine(4)
    .vLine(1.5)
    .hLine(4)
    .vLine(1)
    .hLine(58)
    .vLine(1)
    .hLine(19)
    .vLine(-(2.5+2+3+1.5+1+1)) // .vLineTo(0)
    .close()
    .revolve([1, 0, 0]);

  return inner;
};

```

It's for a toilet paper holder.

Edit: here's the project if you're interested! Always looking for feedback https://github.com/lf94/ToiletPaperHolderCylinder

Feel free to also add it as an example

**Comment by sgenoud** [comment]
Good point! I did not see a use case for the `vLineTo` (it felt like just adding it for symmetry of the interface reasons).

It was fairly simple to do, it is [now in `0.10.0`](https://replicad.pages.dev/docs/api/interfaces/GenericSketcher/#vlineto).

Thanks for the feedback!
